# Generated by Django 2.2.4 on 2019-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goscie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_pokoju', models.CharField(max_length=64)),
                ('ilosc_miejsc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(max_length=64)),
                ('numer_telefonu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_oferty', models.CharField(max_length=64)),
                ('koszt_oferty', models.IntegerField()),
                ('czas_oferty', models.DateTimeField(auto_now_add=True)),
                ('maksymalna_ilość_osob', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rezerwacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_pokoi', models.IntegerField()),
                ('nazwa_pokoju', models.CharField(max_length=64)),
                ('ilosc_miejsc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wydarzenia1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_wydarzenia', models.CharField(max_length=123)),
                ('miejsce_wydarzenia', models.CharField(max_length=64)),
                ('opis_wydarzenia', models.CharField(max_length=300)),
            ],
        ),
    ]
